user/urls.py
"""Defines url patterns for users."""

from django.conf.urls import url
from django.contrib.auth import login
from . import views

urlpatterns = [
    # Login page.
    url(r'^login/$', views.login, name='login'),
        
    # Logout page.
    url(r'^logout/$', views.logout_view, name='logout'),
    
    # Registration page. 
    url(r'^register/$', views.register, name='register'),
]

zheye/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('zheyes.urls','zheyes'),namespace='zheyes')),
    path('users/', include(('user.urls','user'), namespace='user')),
]

zheyes/urls.py
"""Defines url patterns for learning_logs."""

from django.conf.urls import url
from . import views
from django.urls import path, re_path

urlpatterns = [
    # Home page.
    url(r'^$', views.index, name='index'),
    # url(r'^find/$', views.find, name='find'),
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^article/$',views.article,name='article'),
    url(r'^answer/$', views.answer, name='answer'),

]

user/models.py
from django.db import models

# Create your models here.

zheyes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import re
import importlib,sys 
importlib.reload(sys)
# # Create your models here.
# class question(models.Model):
# 	text = models.CharField(max_length=200)
# 	date_added = models.DateTimeField(auto_now_add=True)

# 	def __str__(self):
# 		return self.text


class User(AbstractUser):
    nickname = models.CharField(max_length=50, default='', verbose_name='昵称')
    mobile = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    sex = models.BooleanField('性别', max_length=2, choices=((0, '男'), (1, '女'),), default=0)
    self_description = models.CharField('描述', max_length=256, default='我什么都没写')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __unicode__(self):
        if self.nickname is not None:
            return self.nickname
        else:
            return self.username


class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容')
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='评论用户',on_delete=models.CASCADE)
    thumbsup = models.IntegerField(default=0, verbose_name='点赞量')
    date_publish = models.DateTimeField(auto_now_add=False, verbose_name='发布时间')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return 'id:'+str(self.id)+' '+self.user.nickname


class Article(models.Model):
    content = models.TextField(verbose_name='文章内容')
    thumbsup = models.IntegerField(default=0, verbose_name='点赞量')
    date_publish = models.DateTimeField(auto_now_add=False, verbose_name='发布时间')
    user = models.ForeignKey(User, verbose_name='作者',on_delete=models.CASCADE)
    comment = models.ManyToManyField(Comment, blank=True, null=True, verbose_name='评论')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __unicode__(self):
        return str(self.id)


class Question(models.Model):
    title = models.CharField(max_length=128, verbose_name='问题名')
    desc = models.TextField(max_length=256, verbose_name='文章描述')
    date_publish = models.DateTimeField(auto_now_add=False, verbose_name='发布时间')
    likes = models.IntegerField(default=0, verbose_name='喜欢')
    article = models.ManyToManyField(Article, blank=True, null=True, verbose_name='文章')
    author=models.ForeignKey(User,blank=True, null=True, verbose_name='作者',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '问题'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __unicode__(self):
        return self.title

user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from zheyes.models import User
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
import json
from user.verify import *

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('zheyes:index'))

@csrf_exempt
def register(request):
    """Register a new user."""
    name = request.POST['username']
    nickname = request.POST['nickname']
    phone = request.POST['mobile']
    pwd = request.POST['password']
    pwd2 = request.POST['password2']
    sexget = request.POST['sex']
    if sexget == '男':
        sex = False
    else:
        sex = True
    name_dic = verify_username(name)
    phone_dic = verify_phone(phone)
    pwd_dic = verify_pwd(pwd, pwd2)
    dictMerged = dict(name_dic, **phone_dic, **pwd_dic)
    if dictMerged['phone'] == '' and dictMerged['name'] == '' and dictMerged['pwd'] == '':
        user = User()
        user.username = name
        user.nickname = nickname
        user.mobile = phone
        user.password = pwd
        user.sex = sex
        user.save()
    return HttpResponse(json.dumps(dictMerged))

@csrf_exempt
def login(request):
    if request.method == 'POST':
            name = request.POST['username']
            pwd = request.POST['password']
            user_set =User.objects.filter(username=name, password=pwd)
            client = User()
            for u in user_set:
                client = u
            if client.username:
                request.session['client'] = client
                # serialize('json',client)
                return HttpResponse('ok')
            else:
                return HttpResponse('用户名或密码输入错误')
    else:
        return render(request, 'users/login_reg.html', locals())

zheyes/views.py
from django.shortcuts import render
from .models import Question,User
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from zheyes.handle import *

# Create your views here.
@csrf_exempt
def index(request):
    Qlist = Question.objects.all().order_by('-likes')
    query=getPage(request,Qlist)
    index_content=getIndexPage(query)
    # if request.session['client']:
    #     client = request.session['client']
    #     client.username = 'haha'
    session = request.session
    if session.get('client'):
        client = session['client']
        # print(session['client'])
        # print (type(session['client']))
    return render(request, 'zheyes/index.html', locals())
# def find(request):
# 	context={}
# 	return render(request,'zheyes/find.html',context)
@csrf_exempt
def ask(request):
    if request.method == 'POST':
        client = request.session.get('client', default=None)
        if client:
            q_name = request.POST['question_name']
            q_desc = request.POST['question_description']
            askQuestion(uid=client.id, title=q_name, desc=q_desc)
            return HttpResponse('ok')


@csrf_exempt
def article(request):
    if request.method == 'GET':
        qid = request.GET.get('qid')
        user_id = request.GET.get('user_id')
        comment_text = request.GET.get('comment_text')
        article_id = request.GET.get('article_id')
        if qid:
            ques_article = getArticleCommet(int(qid))
            return render(request, 'zheyes/article_detail.html', locals())
        else:
            saveComment(uid=user_id, content=comment_text, aid=article_id)
            return HttpResponse('ok')
    # return render(request,'zheyes/article_detail.html',locals())


@csrf_exempt
def answer(request):
    if request.method == 'POST':
        user_id = request.POST['user_id']
        question_id = request.POST['question_id']
        article_content = request.POST['article_content']
        saveArticle(uid=user_id, qid=question_id, content=article_content)
        return HttpResponse('ok')
    else:
        qid = request.GET.get('qid')
        client = request.session.get('client', default=None)
        if qid and client:
            question = Question.objects.get(id=qid)
            article = question.article.filter(user_id=client.id)
        return render(request, 'zheyes/answer.html', locals())

		

user/templates/users/login.html
{% extends "zheyes/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock %}

{% block main_content %}
    
  <form method="post" action="{% url 'user:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'zheyes:index' %}" />
  </form>
    
{% endblock %}

user/templates/users/login_form.html
{% load staticfiles %}
<form class="form-horizontal" role="form">
    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input id="username_login" type="text" class="form-control" placeholder="输入用户名"/>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input id="password_login" type="password" class="form-control" placeholder="输入密码"/>
                <small id="tipsforlogin" class="text-danger"></small>
            </div>

        </div>
    </div>
    <button id="loginButton" type="button" class="btn btn-primary btn-lg btn-block">登录</button>
</form>
<script>
    $(document).ready(function () {
        $('#loginButton').click(function () {
            $.ajax({
                url: '{% url 'user:login' %}',
                type: 'POST',
                dataType: 'text',
                data: {
                    'username': $('#username_login').val(),
                    'password': $('#password_login').val()
                },
                success: function (data) {
                    if (data == 'ok') {
                        $(window).attr('location','{% url 'zheyes:index' %}');
                    }
                    else {
                        $('#tipsforlogin').html(data);
                    }
                },
                error: function () {
                    alert('出现错误!')
                }
            });
        });
    });
</script>

user/templates/users/login_reg.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    {% include 'zheyes/static_lib.html' %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-push-4 ">
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <h1><strong class="text-primary">知乎者也</strong></h1>
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-11 col-md-push-1 ">
                    <strong>与世界分享你的知识、经验和见解</strong>
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-10 well">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3">
                            <ul class="nav nav-pills">
                                <li class="active">
                                    <a href="#login" id="login-tab" data-toggle="tab">登陆</a>
                                </li>
                                <li>
                                    <a href="#reg" id="reg-tab" data-toggle="tab">注册</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <br/>
                    <div class="tab-content">
                        <div class="tab-pane fade active in" id="login">
                            {% include 'users/login_form.html' %}
                        </div>
                        <div class="tab-pane fade " id="reg">
                            {% include 'users/reg_form.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>

user/templates/users/reg_form.html
{% load staticfiles %}
<form class="form-horizontal" role="form">

    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input type="text" class="form-control" placeholder="用户名" name="username" id="username_reg" required/>
                <small id="tipsforname" class="text-danger"></small>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input type="text" class="form-control" placeholder="昵称 *可以不写" name="nickname" id="nickname_reg" required/>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input type="text" class="form-control" placeholder="输入手机号" name="mobile" id="mobile_reg" required/>
                <small id="tipsforphone" class="text-danger"></small>
            </div>

        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input type="password" class="form-control" placeholder="输入密码" name="password" id="password_reg"
                       required/>
            </div>

        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <div>
                <input type="password" class="form-control" placeholder="确认密码" name="password2" id="password2_reg"
                       required/>
                <small id="tipsforpwd" class="text-danger"></small>
            </div>

        </div>
    </div>
    <div class="col-xs-2 col-xs-offset-4">
        <div class="form-group ">
            <div class="radio">
                <label><input checked type="radio" name="sex" name="sex" value="男" id="sex"/>男</label>
            </div>
        </div>
    </div>
    <div class="col-xs-2 col-xs-offset-1">
        <div class="form-group ">
            <div class="radio">
                <label><input type="radio" name="sex" value="女"/>女</label>
            </div>
        </div>
    </div>
    <button id="regButton" type="button" class="btn btn-primary btn-lg btn-block">注册</button>
</form>
<script>
    $(document).ready(function () {
        $('#regButton').click(function () {
            var msg = null
            $.ajax({
                url: '{% url "user:register" %}',
                type: 'POST',
                dataType: 'text',
                data: {
                    'username': $('#username_reg').val(),
                    'nickname': $('#nickname_reg').val(),
                    'mobile': $('#mobile_reg').val(),
                    'password': $('#password_reg').val(),
                    'password2': $('#password2_reg').val(),
                    'sex': $('input[type="radio"]:checked').val()
                },
                success: function (data) {
                    msg = JSON.parse(data);
                    if (msg.name == '' && msg.phone == '' && msg.pwd=='') {
                        alert('注册成功！')
                    }
                    else {
                        $('#tipsforname').html();
                        $('#tipsforname').html(msg.name);
                        $('#tipsforphone').html();
                        $('#tipsforphone').html(msg.phone);
                        $('#tipsforpwd').html();
                        $('#tipsforpwd').html(msg.pwd);
                    }
                },
                error: function () {
                    alert('出现错误!')
                }
            });
        });
    });
</script>

user/templates/users/register.html
{% extends "zheyes/base.html" %}

{% block main_content %}

  <form method="post" action="{% url 'user:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next"
      value="{% url 'zheyes:index' %}" />
  </form>
    
{% endblock %}

zheyes/templates/zheyes/answer.html
{% extends 'zheyes/base.html' %}
{% load staticfiles %}
{% block main_content %}

    <link href="{% static 'js/kindeditor-4.1.10/themes/default/default.css' %}" rel="stylesheet">
    <script src="{% static 'js/kindeditor-4.1.10/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'js/kindeditor-4.1.10/lang/zh-CN.js' %}"></script>

    <script>
        var editor;
        KindEditor.ready(function (K) {
            editor = K.create('textarea[name="content"]', {
                resizeType: 1,
                allowPreviewEmoticons: false,
                //
                <!--去掉远程上传的功能-->
                allowImageRemote: false,
                width: '100%',
                height: '500px',
                uploadJson: '/admin/upload/kindeditor',
                afterBlur: function () {
                    this.sync();
                }
            });
        })

    </script>

    <div class="container">
        <div class="well">
            <div class="row">
                <div class="col-md-7 col-md-offset-2">
                    <h3 id="tags" style="color: #2aabd2">{{ question.title }}</h3>
                    <br>
                    <h4 style="color:gray"> {{ question.desc }}</h4>
                </div>

            </div>
        </div>
        <hr>
        <div class="well">
            <div class="row">
                <div class="col-md-8 col-md-offset-1">
                    <textarea id="editor_id" name="content" class="form-control" rows="4">
                           {% autoescape off %}
                               {% for a in article %}
                                   {{ a.content }}
                               {% endfor %}
                           {% endautoescape %}
                    </textarea>
                </div>
                <div class="col-md-1 col-md-offset-1">
                    <button id='saveReply' type="button" class="btn btn-primary">保存提交</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#saveReply').click(function () {
                editor.sync();
{#                alert( $('#editor_id').val());#}
                $.ajax({
                    url: '{% url "zheyes:answer" %}',
                    type: 'post',
                    dataType: 'text',
                    data: {
                        'user_id':{{ client.id }},
                        'question_id':{{ question.id }},
                        'article_content': $('#editor_id').val()
                    },
                    success: function (data) {
                        if (data == 'ok') {
                            $(window).attr('location', '/article?qid={{ question.id }}');
                        }

                    },
                    error: function () {
                        alert('出现错误!')
                    }
                });

            });
        });

    </script>
{% endblock %}

zheyes/templates/zheyes/article_simplified.html
{% load staticfiles %}

{% for index in index_content %}
    <div class="alert alert-info-jerry ">
        <div class="row">
            <div class="col-md-1">
                <a href="/profile/{{ index.article.user.id }}">
                    {% autoescape off %}
                        {{ index.article.user.profile }}
                    {% endautoescape %}
                </a>
            </div>
            <div class="col-md-9 ">
                <a href="/profile/?uid={{ index.article.user.id }}"><h4>{{ index.article.user.nickname }}</h4></a>
                <p>{{ index.article.user.self_description }}</p>
            </div>
            <div class="col-md-2">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <a href="/article?qid={{ index.question_id }}"><h3>{{ index.question_title }}</h3></a>
            </div>
        </div>

        {% autoescape off %}

            {{ index.simple_desc|truncatewords_html:10 }}

        {% endautoescape %}
        <hr/>
        <h4>
            {% load humanize %}
            <span class="glyphicon glyphicon-heart"><code>{{ index.likes }}</code>&nbsp;</span>
            <span class="glyphicon glyphicon-calendar"><code>{{ index.date_publish|date:'Y年 M  j号  D' }}</code>&nbsp;</span>
        </h4>
    </div>
{% endfor %}

<div class="text-center">

    <ul class="pager">
        <li>
            {% if query.has_previous %}
                <a href="?num={{ query.previous_page_number }}&searchText={{ searchText }}">&laquo;上一页</a>
            {% endif %}
        </li>
        {#        Page {{ query.number }} of {{ query.paginator.num_pages }}.#}
        <li >
            <a style="background-color: #5bc0de;color: #0f0f0f">{{ query.number }}</a>
        </li>
        /
        <li>
            <a>{{ query.paginator.num_pages }}</a>
        </li>
        <li>
            {% if query.has_next %}

                <a href="?num={{ query.next_page_number }}&searchText={{ searchText }}">下一页&raquo;</a>

            {% endif %}
        </li>
    </ul>

</div>

zheyes/templates/zheyes/ask_question.html
{% load staticfiles %}
<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">提问</h4>
            </div>
            <div class="modal-body">

                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">问题名:</label>
                        <input type="text" class="form-control" id="question_name">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">问题描述:</label>
                        <textarea class="form-control" rows="5" placeholder="请简洁的描述问题" id="question_description"></textarea>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="question_submit">确认添加</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#question_submit').click(function () {
            //alert($('#question_name').val()+$('#question_description').val()+$('#question_tag').val())
            $.ajax({
                url: '{% url "zheyes:ask" %}',
                type: 'post', 
                dataType: 'text',
                data: {
                    'question_name': $('#question_name').val(),
                    'question_description': $('#question_description').val(),
                },
                success: function (reponseText) {
                    if (reponseText == 'ok') {
                         $('#myModal').modal('hide')
                    }
                },

                error: function () {
                    alert('出现错误!')
                }
            });
        });
    });

</script>

zheyes/templates/zheyes/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    {% include 'zheyes/static_lib.html' %}
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigtion</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'zheyes:index' %}" class="navbar-brand "
                   style="margin-left: 20px;color: #337ab7;font-size: x-large;">
                    知乎者也
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-responsive-collapse">
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input id="searchText" type="text" value="{{ searchStr|default:"" }}" class="form-control" size="50" placeholder="搜索你感兴趣的问题或标签"/>
                    </div>
                    <button   type="button" id="searchButton" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'zheyes:index' %}"><span class="glyphicon glyphicon-home">首页</span></a>

                    </li>

                </ul>

                <ul class="nav navbar-nav">
                    <li>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </li>
                    <li>
                        <button type="button" class="btn btn-primary navbar-btn" data-toggle="modal"
                                data-target="#myModal">提问
                        </button>

                    </li>

{#                    <li>#}
{#                        <a href="{% url 'answer' %}" class="navbar-link" style="color: #337ab7;font-size: 18px;">回答#}
{#                        </a>#}
{#                    </li>#}
                    <li>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </li>
                    <li>
                        {% if client.username %}
                            <a href="" class="dropdown-toggle " data-toggle="dropdown">
                                {% if client.nickname %}
                                    <b>{{ client.nickname }}</b>
                                {% else %}
                                    <b>{{ client.username }}</b>
                                {% endif %}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href=""><span
                                            class="glyphicon glyphicon-home">&nbsp;我的主页</span></a>
                                </li>
                                <li>
                                    <a href=""><span
                                            class="glyphicon glyphicon-envelope">&nbsp;我的私信</span></a>
                                </li>
                                <li>
                                    <a id="logout" href=""><span class="glyphicon glyphicon-off">&nbsp;退出</span></a>
                                </li>
                            </ul>
                        {% else %}
                            <a href="{% url 'user:login' %}">请登录</a>
                        {% endif %}
                    </li>
                    <!-- <li>
{#                        {% if client.username %}#}
{#                            <p>{{ client }}</p>#}
{#                        {% else %}#}
{#                            <p>client不存在</p>#}
{#                        {% endif %}#}
                    </li> -->
                </ul>

            </div>
        </div>
    </div>
</nav>
<script>
    $(document).ready(function () {
        $('#logout').click(function () {
            $.ajax({
                url: "{% url 'user:logout' %}",
                type: 'get',
                dataType: 'text',
                success: function (data) {
                    if (data == 'ok') {
                        $(window).attr('location', '{% url "user:login" %}');
                    }
                    else {
                        alert(data);
                    }
                },
                error: function () {
                    alert('出现错误!')
                }
            });
        });
    });

    $(document).ready(function () {
        $('#searchButton').click(function () {
            var string=$('#searchText').val()
            $(window).attr('location','/?searchText='+string);
        });
    });
</script>

{% include 'zheyes/ask_question.html' %}
<br/> {% block main_content %}{% endblock %}
</body>

</html>

zheyes/templates/zheyes/comment.html
{% load staticfiles %}
<div class="collapse" id="collapseComment{{ i }}">
    <div class="list-group" id="list_group{{ article.id }}">
        {% for com in article.comments %}
            <a class="list-group-item ">
                <div class="row">
                    <div class="col-md-1">

                        {% autoescape off %}
                            {{ com.user.profile }}
                        {% endautoescape %}

                    </div>
                    <div class="col-md-8">
                        <h4>{{ com.user.nickname }}</h4>
                        <p style="color: gray;">{{ com.user.self_description }}</p>
                    </div>
                    <div class="col-md-3">
                        <p>{{ com.date_publish|date:'M  j号 H i' }}发表</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <h4>{{ com.content }}</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-offset-1">
                        {#                        <span class="glyphicon glyphicon-thumbs-up"><code>{{ com.thumbsup }}</code>&nbsp;</span>#}
                        <div class="praise">
                            <span class="praiseParent"><img src="{% static 'img/zan.png' %}" id="praise-img"/></span>
                            <span id="praise-txt">{{ com.thumbsup }}</span>
                            <span id="add-num"><em>+1</em></span>
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}

    </div>
    <div class="list-group">
        <a class="list-group-item ">
            <form>
                <div class="row">
                    <div class="col-md-10">
                        <input type="text" id="comment{{ article.id }}" class="form-control" name="{{ article.id }}"
                               placeholder="来吐槽吧！"/>
                    </div>
                    <div class="col-md-2">
                        <button type="button" name="submitComment" value="comment{{ article.id }}"
                                class="btn btn-primary">提交评论
                        </button>
                    </div>
                </div>
            </form>
        </a>
    </div>

</div>
</div>